version: "3.8"
services:
  app:
    image: uvicorn-gunicorn-fastapi:python3.9
    container_name: fastapi-app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn main:app --reload --host 0.0.0.0